# Generated by Django 5.2.1 on 2025-05-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerdetail',
            options={'ordering': ['title'], 'verbose_name': 'Detail', 'verbose_name_plural': 'Details'},
        ),
    ]
