# Generated by Django 5.2.1 on 2025-05-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.FileField(blank=True, max_length=255, upload_to='static/img/profile-img/'),
        ),
    ]
