# Generated by Django 5.2.1 on 2025-05-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0003_alter_profile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
