# Generated by Django 5.2.1 on 2025-05-27 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0008_alter_profile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 11, 38, 35, 94336, tzinfo=datetime.timezone.utc)),
        ),
    ]
