# Generated by Django 5.2.1 on 2025-05-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0011_profilefile_alter_profile_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilefile',
            options={'ordering': ['file'], 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
    ]
