# Generated by Django 5.2.1 on 2025-06-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0012_alter_profilefile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='working_hours',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
