# Generated by Django 5.2.1 on 2025-05-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0003_alter_offer_updated_at'),
        ('order_app', '0002_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='offer',
        ),
        migrations.AddField(
            model_name='order',
            name='offer_detail',
            field=models.ManyToManyField(related_name='orders', to='offer_app.offerdetail'),
        ),
    ]
