# Generated by Django 5.2.1 on 2025-05-30 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0003_alter_offer_updated_at'),
        ('order_app', '0003_remove_order_offer_order_offer_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='offer_detail',
        ),
        migrations.AddField(
            model_name='order',
            name='offer_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='offer_app.offerdetail'),
        ),
    ]
