# Generated by Django 5.2.1 on 2025-06-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['pk'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
